name: Test
on: push
jobs:
  test-with-tests-arg:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run unit tests
      uses: ./
      with:
        tests: tests
        src: tests
  test-without-tests-arg:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run unit tests
      uses: ./
      with:
        src: tests
  test-with-logfile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run unit tests
      uses: ./
      with:
        src: tests
        log_file: log.txt
    - uses: actions/upload-artifact@v1
      with:
        name: log_file
        path: log.txt