name: Test
on: push
jobs:
  test-with-tests-arg:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run unit tests
      uses: ./
      with:
        tests: tests
        src: tests
  test-without-tests-arg:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run unit tests
      uses: ./
      with:
        src: tests
  test-with-logfile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run unit tests
      uses: ./
      with:
        src: tests
        log_file: log.txt
    - uses: actions/upload-artifact@v1
      with:
        name: log_file
        path: log.txt
  test-documentation-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run unit tests
      uses: ./
      with:
        src: tests
        doc_tests: true
  test-with-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run unit tests
      uses: ./
      with:
        src: tests
        with_coverage: true
  test-cover-xml-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run unit tests
      uses: ./
      with:
        src: tests
        cover_xml_file: coverage.xml
    - uses: actions/upload-artifact@v1
      with:
        name: coverage_file
        path: coverage.xml
  test-cover-html-dir:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run unit tests
      uses: ./
      with:
        src: tests
        cover_html_dir: htmlcov
    - uses: actions/upload-artifact@v1
      with:
        name: coverage_html
        path: htmlcov